-- Goal statuses: single source of truth for AI-determined status (On track / At risk / Failing)
-- Synced across devices; localStorage used only as instant-load cache.

create table if not exists public.goal_statuses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  goal_id bigint not null references public.goals(id) on delete cascade,
  status text not null check (status in ('On track', 'At risk', 'Failing')),
  updated_at timestamptz default now() not null,
  unique(user_id, goal_id)
);

create index if not exists goal_statuses_user_id_idx on public.goal_statuses(user_id);

alter table public.goal_statuses enable row level security;

create policy "Users can manage own goal statuses"
  on public.goal_statuses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
